# Generated by Django 4.2.7 on 2024-09-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="Category",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
