# Generated by Django 4.2.7 on 2024-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_rename_category_blog_category_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="Category_name",
            new_name="category_name",
        ),
    ]
