# Generated by Django 5.1.1 on 2024-09-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_rename_comment_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
