# Generated by Django 5.1.1 on 2024-09-15 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0007_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
